/* create database clinic  */
create database clinic;

/* create table patients */
CREATE TABLE patients (
    id  int always generated by identity,
    name  varchar(30),
    date_of _birth  date,
    PRIMARY KEY (id)
);

/* create table patients_medical_history */

CREATE TABLE medical_histories (
   id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   admitted_at TIMESTAMP,
   patient_id INT REFERENCES patients(id),
   status VARCHAR(30)
);
